#!/bin/bash

set -e
set -x

mv /usr/sbin/policy-rc.d.disabled /usr/sbin/policy-rc.d
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install ntp
chgrp root /var/lib/ntp
chmod g+w /var/lib/ntp
apt-get -y -u dist-upgrade
apt-get clean
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
/usr/local/bin/docker-wipelogs

mv /usr/sbin/policy-rc.d /usr/sbin/policy-rc.d.disabled
